# app.cors.allowed-origins=http://localhost:5173,https://securevault-three.vercel.app
app.cors.allowed-origins=${CORS_ORIGINS}

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME} 
spring.datasource.password=${DATABASE_PASSWORD}

app.jwt.secret= VQQkiQ5v5mYiLh7t7Zz+8keGJmmZZ5o2HQOeUWKt8DJ18GFDD9918v4xhYCu/dDtGvQ41+rMBSyqR8mC43iVhw==
app.encryption.key=AwylRxwd/1KFyl4rSIP1l29TO5/2TE2FaDTplAWFV0s=

server.port=8080
spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=hemanthchitta98@gmail.com
spring.mail.password=viohphazepnqyzan

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.frontend.url=http://localhost:5173, https://securevault-three.vercel.app